module.exports = {
    MISSING_NICKNAME: "MISSING_NICKNAME",
    MISSING_SONG_LIST: "MISSING_SONG_LIST",
    LIST_OVERFLOW: "LIST_OVERFLOW",
    ALREADY_EXISTS: "ALREADY_EXISTS",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
}