version: "3"
services:
    mongo:
        container_name: mongo
        image: "mongo:latest"
        ports:
            - "27017:27017"
        volumes:
            - /data/mongodb/db:/data/db
    web_admin:
        container_name: admin
        build:
            context: ../backend/admin
        ports:
            - "5000:5000"
        volumes:
            - "../backend/admin:/usr/src/app"
            - "/usr/src/app/node_modules"
        environment:
            - PORT=5000
            - CORES=2
            - MONGO_ACCESS=mongodb://mongo/cit
        links:
            - mongo
    web_submit:
        container_name: submit
        build:
            context: ../backend/submit
        volumes:
            - "../backend/submit:/usr/src/app"
            - "/usr/src/app/node_modules"
        ports:
            - "5001:5001"
        environment:
            - PORT=5001
            - CORES=2
            - MONGO_ACCESS=mongodb://mongo/cit
        links:
            - mongo
    react:
        container_name: react
        build:
            context: ../frontend/
        volumes:
            - "../frontend:/usr/src/app"
            - "/usr/src/app/node_modules"
        ports:
            - "3000:3000"
